library/library/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('library_app/', include('library_app.urls')),
    path('admin/', admin.site.urls),
]

library/library_app/urls.py
from django.urls import path

from . import views

app_name = 'library_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('available-books/', views.view_all_available_books, name='available-books'),
    path('students-books/', views.students_books, name='students-books'),
    path('<int:student_id>/student-books/', views.student_books, name='student-books'),
    path('student-operation/', views.student_operation, name='student-operation'),
    path('make-operation/', views.make_operation, name='make-operation'),
]

library/library_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=20)
    group = models.IntegerField()

    def __str__(self):
        return 'name: ' + str(self.name) + ', group: ' + str(self.group)

class Book(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=20)
    description = models.CharField(max_length=500)
    current_student = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True,
            null = True)

    def __str__(self):
        return 'id: '+ str(self.id) + ', ' +  'name: ' + str(self.name) + ', author: ' + str(self.author) + ', description: ' + str(self.description)

library/library_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader

from .models import Book, Student

def index(request):
    context = {}
    template = loader.get_template('library_app/index.html')
    return HttpResponse(template.render(context, request))

def view_all_available_books(request):
    books = Book.objects.all().filter(current_student__isnull=True)
    res = ''
    for b in books:
        res += str(b) + ';'
    return HttpResponse(f"Available books in library: {res}")

def student_operation(request):
    context = {}
    template = loader.get_template('library_app/take_or_return_book.html')
    return HttpResponse(template.render(context, request))

def make_operation(request):
    student_id = request.POST['student']
    book_id = request.POST['book']
    operation = request.POST['operation']
    book = get_object_or_404(Book, pk=book_id)
    student = get_object_or_404(Student, pk=student_id)
    if operation == 'take':
        if book.current_student:
            return HttpResponse(f'Book {book_id} is taken by other student')
        book.current_student = student
        book.save()
        return HttpResponse('Done')
    elif operation == 'return':
        if not book.current_student:
            return HttpResponse(f'Book {book_id} is free')
        if book.current_student != student:
            return HttpResponse(f'Book {book_id} is taken by other student')
        book.current_student = None
        book.save()
        return HttpResponse('Done')
    else:
        return HttpResponse(f'Wrong operation: {operation}')

def students_books(request):
    students = Student.objects.all()
    context = {'students_list': students}
    template = loader.get_template('library_app/student_books.html')
    return HttpResponse(template.render(context, request))

def student_books(request, student_id):
    taken_books = []
    books = Book.objects.all()
    student = get_object_or_404(Student, pk=student_id)
    for b in books.all():
        if b.current_student == student:
            taken_books.append(b)
    res = ''.join(str(e) + '<br>' for e in taken_books)
    return HttpResponse(f'Taken books for student {student_id}: {res}')

library/library_app/templates/library_app/index.html
<a href="/library_app/available-books">See all available books</a>
<br>
<a href="/library_app/students-books">See all books taken by student </a>
<br>
<a href="/library_app/student-operation">Return or take a book</a>

library/library_app/templates/library_app/student_books.html
{% if students_list %}
    Registered students:
    <ul>
    {% for student in students_list %}
    <li><a href="{% url 'library_app:student-books' student.id %}">{{ student.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No students registered.</p>
{% endif %}

library/library_app/templates/library_app/take_or_return_book.html
 <form action="{% url 'library_app:make-operation' %}" method="post">
  {% csrf_token %}
  Student id:<br>
  <input type="text" name="student"><br>
  Book id:<br>
  <input type="text" name="book">
  <br>"take" or "return":<br>
  <input type="text" name="operation">
  <input type="submit" value="Submit">
</form> 